//
//  DetailedRouter.swift
//  RXSwiftVIPER
//
//  Created by Alisher Saideshov on 16.04.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailedRoutingLogic {
}

protocol DetailedDataPassing {
    var dataStore: DetailedDataStore? { get }
}

class DetailedRouter: NSObject, DetailedRoutingLogic, DetailedDataPassing {
    weak var viewController: DetailedViewController?
    var dataStore: DetailedDataStore?

    // MARK: Routing

}
