//
//  DetailedModels.swift
//  RXSwiftVIPER
//
//  Created by Alisher Saideshov on 16.04.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detailed {
    // MARK: Use cases

    enum displayDetailedInformation {
        struct Response {
            let name: String
            let species: String
            let image: UIImage
        }
        struct ViewModel {
            let name: String
            let species: String
            let image: UIImage
        }
    }
}
