//
//  DetailedPresenter.swift
//  RXSwiftVIPER
//
//  Created by Alisher Saideshov on 16.04.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import UIKit

protocol DetailedPresentationLogic {
    func presentDetailedInformation(response: Detailed.displayDetailedInformation.Response)
}

class DetailedPresenter: DetailedPresentationLogic {
    weak var viewController: DetailedDisplayLogic?

    // MARK: Do something

    func presentDetailedInformation(response: Detailed.displayDetailedInformation.Response) {
        let name = "Character name: " + response.name
        let species = "Character species: " + response.species
        let viewModel = Detailed.displayDetailedInformation.ViewModel(
            name: name,
            species: species,
            image: response.image)
        viewController?.displayCharacterInformation(viewModel: viewModel)
    }
}
