//
//  CleanSwiftModels.swift
//  RXSwiftVIPER
//
//  Created by Alisher Saideshov on 15.04.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    // MARK: Use cases

    enum displayCartoonCharacters {
        struct Request {
        }
        struct Response {
            let characters: [CharResult]
        }
        struct ViewModel {
            struct characterInformationModel {
                let id: Int
                let name: String
                let species: String
            }
            var characterInformation: [characterInformationModel]
        }
    }
}
